vich_uploader:
  db_driver: orm # or mongodb or phpcr

  mappings:
    agent_thumbnail:
      uri_prefix: /images/agent
      upload_destination: '%kernel.project_dir%/public/images/agent'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    property_photo:
      uri_prefix: /images/property
      upload_destination: '%kernel.project_dir%/public/images/property'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
